# Exceptions

try:
    result = 1/0
    print(result)
except:
    print("failed")